# Site settings
title: "&lt;mxstbr/&gt;"
url-title: "Max Stoiber"
description: "Blogging about HTML, CSS, JavaScript and the Web"
paginate: 1
url: "http://mxstbr.com"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed