# Site settings
title: "&lt;mxstbr/&gt;"
url-title: "Max Stoibers Blog"
description: "Fresh thinking, expert tips and great insights about HTML, CSS, JavaScript and other web technologies."
paginate: 50
url: "http://blog.mxstbr.com"
permalink: /:year/:month/:title
future: false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [smart, no_intra_emphasis, tables, fenced_code_blocks, autolink, lax_spacing, footnotes, disable_indented_code_blocks, superscript, with_toc_data]
sass:
  sass_dir: _sass
  style: compressed
  deploy_style: compressed